import React,{useState} from 'react';
import {Routes,Route,useNavigate,useLocation,Link,Navigate} from 'react-router-dom';
import {HeartPulse,Menu,Bell,Search,ShieldCheck,Brain,HandHeart,Users,ArrowRight,Phone,BookOpen,UserRound,Settings,LogOut,Stethoscope,Activity,Mail,MapPin,Clock,Send,CheckCircle2,Heart,AlertCircle,CalendarDays,Pill,FileText,AlertTriangle,ClipboardList,Download,ExternalLink} from 'lucide-react';
import {cancerTypes,cancerCategories,mentalTopics} from './data/data';

const Logo=()=> <Link className="logo" to="/"><span className="logoMark"><HeartPulse size={23}/></span><span>Care <b>Nexus</b></span></Link>;
const Button=({children,to,onClick,secondary=false,type='button',className=''})=> to?<Link to={to} className={`btn ${secondary?'btnSecondary':''} ${className}`}>{children}</Link>:<button type={type} onClick={onClick} className={`btn ${secondary?'btnSecondary':''} ${className}`}>{children}</button>;

function PublicNav(){const [open,setOpen]=useState(false); return <header className="topbar"><Logo/><button className="mobileMenu" onClick={()=>setOpen(!open)}><Menu/></button><nav className={open?'nav open':'nav'}><Link to="/">Home</Link><Link to="/about">About Us</Link><Link to="/cancer">Cancer</Link><Link to="/symptoms">Symptoms</Link><Link to="/mental-health">Mental Health</Link><Link to="/resources">Resources</Link><Button to="/login" secondary>Login</Button><Button to="/signup">Sign Up</Button></nav></header>}
function Footer(){return <footer><div className="footerMain"><div><Logo/><p>Cancer awareness, mental health support and practical health resources in one place.</p></div><div><h4>Explore</h4><Link to="/cancer">Cancer Information</Link><Link to="/symptoms">Symptoms</Link><Link to="/mental-health">Mental Health</Link><Link to="/emergency">Emergency Guidance</Link></div><div><h4>Support</h4><Link to="/donate">Donate / Support</Link><Link to="/contact">Contact Us</Link><Link to="/dashboard">User Dashboard</Link></div></div><div className="footerBottom">© {new Date().getFullYear()} CareNexus. Educational health information only.</div></footer>}
function Shell({children}){return <><PublicNav/>{children}<Footer/></>}

const Feature=({icon,title,text,to='/cancer'})=><div className="feature card"><div className="featureIcon">{icon}</div><h3>{title}</h3><p>{text}</p><Link to={to}>Explore <ArrowRight size={14}/></Link></div>;
function Home(){return <Shell><main><section className="hero"><div className="heroCopy"><span className="eyebrow">Cancer Awareness & Mental Well-being</span><h1>Care. Connect.<br/><em>Support.</em></h1><p>CareNexus brings cancer information, symptom awareness, emergency guidance, mental health support and patient tools into one simple experience.</p><div className="actions"><Button to="/cancer">Cancer Information</Button><Button to="/mental-health" secondary>Mental Health Support</Button></div></div><MedicalArt/></section><section className="section"><h2 className="center">Quick Access</h2><div className="featureGrid"><Feature icon={<ShieldCheck/>} title="Cancer Information" text="Explore cancer types, symptoms, risk factors, prevention, diagnosis and treatment."/><Feature icon={<AlertTriangle/>} title="Symptoms & Emergency" text="Learn warning signs and when to seek urgent professional help." to="/symptoms"/><Feature icon={<Pill/>} title="Medicine Reminder" text="Keep a simple list of medicines, doses and schedules in your dashboard." to="/medicine"/><Feature icon={<Brain/>} title="Mental Health Support" text="Explore stress, anxiety, depression, coping strategies and support resources." to="/mental-health"/></div></section><section className="splitSection"><div className="why card"><div><h2>CareNexus Patient Support</h2><ul><li><CheckCircle2/>Cancer awareness and educational information</li><li><CheckCircle2/>Mental health and emotional support resources</li><li><CheckCircle2/>Appointments and treatment tracking</li><li><CheckCircle2/>Donation and community support information</li></ul></div><div className="shieldArt"><Heart size={100}/></div></div><div className="miniLogin card"><div><Logo/><h3>Need your dashboard?</h3><p>Manage reminders, appointments and your profile.</p><Button to="/dashboard">Open Dashboard</Button></div><MedicalArt compact/></div></section></main></Shell>}
function MedicalArt({compact=false}){return <div className={`medicalArt ${compact?'compact':''}`}><div className="artCircle"></div><div className="heartShape"><HeartPulse size={compact?85:145}/></div><Stethoscope className="steth" size={compact?100:150}/><span className="plus">+</span></div>}

function DashboardLayout({children}){const nav=useNavigate();const loc=useLocation();const [side,setSide]=useState(false); const links=[['/dashboard','Dashboard',BookOpen],['/cancer','Cancer Information',Activity],['/symptoms','Symptoms',AlertTriangle],['/emergency','Emergency Guidance',AlertCircle],['/medicine','Medicine Reminder',Pill],['/appointments','Appointments',CalendarDays],['/mental-health','Mental Health',Heart],['/resources','Resources',FileText],['/donate','Donate / Support',HandHeart],['/profile','My Profile',UserRound],['/settings','Settings',Settings]];return <div className="dashPage"><header className="dashTop"><Logo/><div className="dashActions"><button><Bell size={18}/></button><div className="avatar">U</div></div></header><button className="dashToggle" onClick={()=>setSide(!side)}><Menu/></button><aside className={side?'sidebar show':'sidebar'}>{links.map(([to,label,Icon])=><Link className={loc.pathname===to?'active':''} to={to} key={to}><Icon size={16}/>{label}</Link>)}<button className="logout" onClick={()=>nav('/')}><LogOut size={16}/>Logout</button></aside><div className="dashContent">{children}</div></div>}

function Dashboard(){return <DashboardLayout><div className="dashHead"><div><h1>Welcome to CareNexus</h1><p>Your cancer awareness and mental well-being resources are in one place.</p></div><SearchBox placeholder="Search..."/></div><div className="statGrid"><Stat title="Cancer Types" value={`${cancerTypes.length}`} icon="🎗️"/><Stat title="Mental Health Topics" value={`${mentalTopics.length}`} icon="🧠"/><Stat title="Upcoming Tools" value="2" icon="📅"/><Stat title="Support Resources" value="24/7" icon="💗"/></div><section><h2>Quick Actions</h2><div className="topicGrid"><QuickCard to="/cancer" icon="🎗️" title="Cancer Information" text="Types, symptoms, prevention and treatment"/><QuickCard to="/medicine" icon="💊" title="Medicine Reminder" text="Add and review your medicines"/><QuickCard to="/appointments" icon="📅" title="Appointments" text="Track visits, tests and treatment notes"/></div></section><div className="donateBanner"><div><h2>Support a Cause, Save a Life</h2><p>Explore cancer organizations and support resources.</p><Button to="/donate">Donate / Support</Button></div><div className="donateVisual">❤️</div></div></DashboardLayout>}
const Stat=({title,value,icon})=><div className="stat card"><span>{title}</span><b>{value}</b><small>{icon} &nbsp;Explore <ArrowRight size={12}/></small></div>;
const QuickCard=({to,icon,title,text})=><Link to={to} className="topicCard card"><div className="topicImg teal">{icon}</div><div><h3>{title}</h3><p>{text}</p><span>Open <ArrowRight size={13}/></span></div></Link>;
function SearchBox({value,onChange,placeholder='Search...'}){return <div className="searchBox"><Search size={17}/><input value={value} onChange={e=>onChange?.(e.target.value)} placeholder={placeholder}/></div>}

function Cancer(){const [q,setQ]=useState('');const [cat,setCat]=useState('All');const filtered=cancerTypes.filter(d=>(d.name.toLowerCase().includes(q.toLowerCase())||d.summary.toLowerCase().includes(q.toLowerCase()))&&(cat==='All'||d.category===cat));return <DashboardLayout><PageHero title="Cancer Information" text="An educational hub covering cancer types, symptoms, risk factors, prevention, diagnosis and treatment." art="cancer"/><div className="filterBar"><SearchBox value={q} onChange={setQ} placeholder="Search cancer type..."/><div className="chips">{cancerCategories.map(c=><button key={c} className={cat===c?'chip active':'chip'} onClick={()=>setCat(c)}>{c}</button>)}</div></div><div className="diseaseGrid">{filtered.map(d=><CancerCard d={d} key={d.id}/>)}{!filtered.length&&<Empty text="No cancer types match your search."/>}</div><div className="notice"><AlertCircle/> Cancer information is educational and does not replace diagnosis or treatment from a qualified healthcare professional.</div></DashboardLayout>}
const CancerCard=({d})=><Link to={`/cancer/${d.id}`} className="diseaseCard card"><div className={`diseaseIcon ${d.color}`}>{d.icon}</div><h3>{d.name}</h3><p>{d.summary}</p><span>Read More <ArrowRight size={13}/></span></Link>;
function CancerDetails(){const id=useLocation().pathname.split('/').pop();const d=cancerTypes.find(x=>x.id===id);if(!d)return <Navigate to="/cancer"/>;return <DashboardLayout><div className="detailHead"><Link to="/cancer">Home › Cancer Information</Link><div className={`bigDiseaseIcon ${d.color}`}>{d.icon}</div><h1>{d.name}</h1><p>{d.summary}</p></div><div className="detailGrid"><InfoBlock title="Overview"><p>{d.details.overview}</p></InfoBlock><InfoBlock title="Causes & Risk Factors"><p>{d.details.causes}</p></InfoBlock><InfoBlock title="Common Symptoms"><ul>{d.details.symptoms.map(x=><li key={x}>{x}</li>)}</ul></InfoBlock><InfoBlock title="Prevention"><ul>{d.details.prevention.map(x=><li key={x}>{x}</li>)}</ul></InfoBlock><InfoBlock title="Diagnosis"><p>Diagnosis depends on the suspected cancer and may involve a clinical examination, imaging, laboratory tests and tissue testing such as a biopsy. A healthcare professional determines which tests are appropriate.</p></InfoBlock><InfoBlock title="Treatment"><p>{d.details.care}</p></InfoBlock><InfoBlock title="Myths & Facts"><ul><li>Myth: A symptom automatically means cancer. Fact: Many symptoms have non-cancer causes and need proper evaluation.</li><li>Myth: One treatment works for every cancer. Fact: Treatment depends on cancer type, stage and individual factors.</li></ul></InfoBlock></div><div className="notice"><AlertCircle/> Seek professional medical advice for persistent or concerning symptoms. Do not use this page to self-diagnose.</div></DashboardLayout>}
const InfoBlock=({title,children})=><article className="infoBlock card"><h2>{title}</h2>{children}</article>;
const PageHero=({title,text,art})=><section className="pageHero"><div><Link to="/">Home</Link><h1>{title}</h1><p>{text}</p></div><div className="pageHeroArt">{art==='cancer'?<><span>🎗️</span><span>🩺</span></>:art==='doctor'?<><span>🧑‍⚕️</span><span>🩺</span></>:<Brain size={100}/>}</div></section>;

function Symptoms(){return <DashboardLayout><PageHero title="Cancer Symptoms" text="Learn about common warning signs and when persistent changes should be checked by a healthcare professional." art="doctor"/><div className="detailGrid"><InfoBlock title="Common warning signs"><ul>{['Unexplained weight loss','Persistent fatigue','A new lump or swelling','Unusual bleeding or discharge','Persistent cough or hoarseness','Changes in bowel or bladder habits','Persistent pain without a clear cause','Skin changes or a sore that does not heal'].map(x=><li key={x}>{x}</li>)}</ul></InfoBlock><InfoBlock title="Symptoms by cancer type"><p><b>Breast:</b> new breast or underarm lump, nipple or skin changes.</p><p><b>Lung:</b> persistent cough, coughing blood, chest pain or shortness of breath.</p><p><b>Blood:</b> persistent fever, unusual tiredness, frequent infections or easy bruising.</p><p><b>Skin:</b> new or changing spots, non-healing sores or bleeding lesions.</p></InfoBlock><InfoBlock title="When to consult a doctor"><p>Many cancer-like symptoms have other causes. If a symptom is new, persistent, worsening or unusual for you, arrange a medical assessment rather than trying to diagnose it yourself.</p></InfoBlock><InfoBlock title="General health guidance"><p>Keep track of persistent changes, bring your medication and family-history information when relevant, and follow screening recommendations appropriate to your age and risk.</p></InfoBlock></div></DashboardLayout>}

function Emergency(){return <DashboardLayout><PageHero title="Emergency Guidance" text="This page provides general guidance and is not a substitute for emergency services." art="doctor"/><div className="detailGrid"><InfoBlock title="Emergency warning signs"><ul><li>Severe difficulty breathing</li><li>Uncontrolled or heavy bleeding</li><li>Loss of consciousness or a new seizure</li><li>Severe chest pain or sudden serious deterioration</li><li>Any immediate danger to yourself or another person</li></ul></InfoBlock><InfoBlock title="What to do immediately"><p>Contact your local emergency service or go to the nearest emergency department. Do not delay urgent care while searching online for an explanation.</p><p>In Punjab, Pakistan, Rescue 1122 is the emergency response number.</p></InfoBlock><InfoBlock title="Cancer-related urgent concerns"><p>For a person receiving cancer treatment, severe breathing problems, heavy bleeding, sudden confusion, severe allergic reactions or rapidly worsening symptoms require urgent professional assessment.</p></InfoBlock><InfoBlock title="Emergency resources"><p><b>Rescue 1122:</b> 1122 in Punjab, Pakistan.</p><p><b>Mental health crisis:</b> if there is immediate risk of self-harm, contact local emergency services or go to the nearest emergency department.</p></InfoBlock></div></DashboardLayout>}

function Medicine(){const [items,setItems]=useState([]);const [name,setName]=useState('');const [dose,setDose]=useState('');const [time,setTime]=useState('');const add=e=>{e.preventDefault();if(!name)return;setItems([...items,{name,dose,time,status:'Upcoming'}]);setName('');setDose('');setTime('')};return <DashboardLayout><PageHero title="Medicine Reminder" text="A simple frontend reminder list for medicines, dosage and schedules." art="doctor"/><div className="donationGrid"><form className="formCard card" onSubmit={add}><h2>Add Medicine</h2><label>Medicine name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="e.g. Medicine name"/></label><label>Dosage<input value={dose} onChange={e=>setDose(e.target.value)} placeholder="e.g. 500 mg"/></label><label>Schedule<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><Button type="submit"><Pill size={16}/>Add Medicine</Button></form><div className="formCard card"><h2>Upcoming Medicines</h2>{items.length===0?<p className="infoBlock p">No medicines added yet.</p>:items.map((x,i)=><div className="topicCard card" style={{marginBottom:10}} key={i}><div className="topicImg teal">💊</div><div><h3>{x.name}</h3><p>{x.dose||'Dose not entered'} · {x.time}</p><span>{x.status}</span></div></div>)}</div></div></DashboardLayout>}

function Appointments(){const [items,setItems]=useState([]);const [title,setTitle]=useState('');const [date,setDate]=useState('');const [note,setNote]=useState('');const add=e=>{e.preventDefault();if(!title||!date)return;setItems([...items,{title,date,note}]);setTitle('');setDate('');setNote('')};return <DashboardLayout><PageHero title="Appointment & Treatment Tracker" text="Track upcoming appointments, tests, scans, treatment milestones and notes in this frontend demo." art="doctor"/><div className="donationGrid"><form className="formCard card" onSubmit={add}><h2>Add Appointment / Treatment Event</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="e.g. Oncology appointment"/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Notes<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Tests, scans, questions or notes"/></label><Button type="submit"><CalendarDays size={16}/>Add Event</Button></form><div className="formCard card"><h2>Upcoming Appointments</h2>{items.length===0?<p className="infoBlock p">No appointments added yet.</p>:items.map((x,i)=><article className="infoBlock card" key={i}><h2>{x.title}</h2><p>{x.date}</p><p>{x.note||'No notes added.'}</p></article>)}</div></div><div className="detailGrid" style={{marginTop:18}}><InfoBlock title="Tests & Scans"><p>Use appointment notes to record planned or completed tests and scans.</p></InfoBlock><InfoBlock title="Treatment Timeline"><p>Add major treatment events as dated entries so they can be reviewed chronologically.</p></InfoBlock></div></DashboardLayout>}

function MentalHealth(){const [q,setQ]=useState('');const topics=mentalTopics.filter(t=>t.name.toLowerCase().includes(q.toLowerCase()));return <DashboardLayout><PageHero title="Mental Health & Support" text="Support for anxiety, stress, depression and everyday emotional well-being alongside cancer care." art="brain"/><div className="filterBar"><SearchBox value={q} onChange={setQ} placeholder="Search mental health topics..."/></div><div className="mentalGrid">{topics.map(t=><article className="mentalCard card" key={t.id}><div className="mentalIcon">{t.icon}</div><h2>{t.name}</h2><p>{t.summary}</p><Link to={`/mental-health/${t.id}`}>Explore <ArrowRight size={14}/></Link></article>)}</div><div className="supportBox"><h2>Need professional support?</h2><p>If feelings are persistent, severe, or affecting everyday life, consider speaking with a qualified mental health professional. If there is immediate danger, use emergency services.</p><Button to="/emergency">Emergency Guidance</Button></div></DashboardLayout>}
function MentalDetail(){const id=useLocation().pathname.split('/').pop();const t=mentalTopics.find(x=>x.id===id);if(!t)return <Navigate to="/mental-health"/>;return <DashboardLayout><div className="simpleDetail"><span className="mentalIcon big">{t.icon}</span><h1>{t.name}</h1><p>{t.summary}</p><div className="detailGrid"><InfoBlock title="Understanding this topic"><p>Mental health experiences vary. Notice patterns, use supportive coping strategies and seek professional help when symptoms interfere with daily life.</p></InfoBlock><InfoBlock title="Helpful habits"><ul><li>Keep a consistent sleep routine.</li><li>Stay connected with supportive people.</li><li>Use breathing, grounding or relaxation techniques.</li><li>Maintain regular movement and balanced meals where appropriate.</li><li>Consider professional support when needed.</li></ul></InfoBlock></div></div></DashboardLayout>}

function Resources(){return <DashboardLayout><PageHero title="Resources" text="Articles, FAQs, awareness material and useful external health information." art="brain"/><div className="detailGrid"><InfoBlock title="Cancer awareness"><p><a href="https://www.who.int/news-room/fact-sheets/detail/cancer" target="_blank" rel="noreferrer">WHO — Cancer fact sheet <ExternalLink size={12}/></a></p><p><a href="https://www.cancer.gov/types" target="_blank" rel="noreferrer">NCI — Cancer types <ExternalLink size={12}/></a></p><p><a href="https://www.cancer.gov/about-cancer/diagnosis-staging/symptoms" target="_blank" rel="noreferrer">NCI — Cancer symptoms <ExternalLink size={12}/></a></p></InfoBlock><InfoBlock title="FAQs"><p><b>Does every symptom mean cancer?</b> No. Many symptoms have non-cancer causes, but persistent or unusual changes should be medically assessed.</p><p><b>Is one treatment used for every cancer?</b> No. Treatment depends on cancer type, stage and individual circumstances.</p></InfoBlock><InfoBlock title="Awareness material"><p>Use the Cancer Information and Symptoms sections for educational content. A downloadable-resource feature can be connected to a backend later.</p><Button to="/cancer" secondary>Explore Cancer Information</Button></InfoBlock><InfoBlock title="Mental health support"><p>Use the Mental Health & Support section for coping information and guidance on seeking professional help.</p><Button to="/mental-health" secondary>Open Mental Health</Button></InfoBlock></div></DashboardLayout>}

function Donate(){const [sent,setSent]=useState(false);return <Shell><main className="publicPage"><PageHero title="Donate / Support" text="Explore organizations and support options. This frontend demo does not process real payments." art="cancer"/><div className="donationGrid"><div className="donationIntro card"><Heart size={50}/><h2>Support cancer care and awareness</h2><p>Donation information can be connected to verified organizations and real payment providers when a backend is added.</p><ul><li>Cancer patient assistance</li><li>Cancer awareness programs</li><li>Community support</li></ul></div><div className="formCard card"><h2>Support resources</h2><p>For real donations, verify the organization and use its official donation page.</p><p><a href="https://www.who.int/health-topics/cancer" target="_blank" rel="noreferrer">WHO Cancer resources <ExternalLink size={12}/></a></p><Button to="/contact" secondary>Contact Us</Button></div></div></main></Shell>}

function Contact(){const [sent,setSent]=useState(false);return <Shell><main className="publicPage"><PageHero title="Contact Us" text="Have a question or suggestion? Send us a message." art="brain"/><div className="contactGrid"><div className="contactInfo card"><h2>Get in touch</h2><p>This frontend demo shows the form interaction without sending data to a server.</p><div><Mail/> support@carenexus.demo</div><div><Phone/> +92 300 0000000</div><div><MapPin/> Lahore, Pakistan</div><div><Clock/> Mon–Fri, 9:00–17:00</div></div><form className="formCard card" onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Subject<input required placeholder="How can we help?"/></label><label>Message<textarea required rows="6" placeholder="Write your message..."></textarea></label><Button type="submit"><Send size={16}/>{sent?'Message sent':'Send Message'}</Button>{sent&&<p className="success"><CheckCircle2/> Thanks! Your demo message was submitted.</p>}</form></div></main></Shell>}

function About(){return <Shell><main className="publicPage"><PageHero title="About CareNexus" text="A simple platform focused on cancer awareness, mental well-being and patient support tools." art="brain"/><section className="aboutGrid"><InfoBlock title="Our Mission"><p>CareNexus organizes cancer education, symptom awareness, mental health support and practical patient tools in one accessible interface.</p></InfoBlock><InfoBlock title="Our Approach"><p>Information is presented for education and awareness. Diagnosis and treatment decisions should be made with qualified healthcare professionals.</p></InfoBlock><InfoBlock title="Privacy & Safety"><p>This project is a frontend demo. Do not enter sensitive medical or financial information into an untrusted form.</p></InfoBlock></section></main></Shell>}

function Login({signup=false}){const nav=useNavigate();const submit=e=>{e.preventDefault();nav('/dashboard')};return <div className="authPage"><div className="authCard card"><Logo/><div className="authArt"><MedicalArt compact/></div><h1>{signup?'Create your account':'Welcome Back!'}</h1><p>{signup?'Join CareNexus and explore cancer and mental health resources.':'Login to your CareNexus account.'}</p><form onSubmit={submit}>{signup&&<label>Full Name<input required placeholder="Your name"/></label>}<label>Email<input required type="email" placeholder="you@example.com"/></label><label>Password<input required type="password" minLength="6" placeholder="••••••••"/></label><Button type="submit">{signup?'Create Account':'Login'}</Button></form><small>{signup?'Already have an account? ':'Don’t have an account? '}<Link to={signup?'/login':'/signup'}>{signup?'Login':'Sign Up'}</Link></small></div></div>}

function Profile(){return <DashboardLayout><div className="settingsPage card"><div className="profileBig">U</div><h1>My Profile</h1><p>Manage basic personal and health-profile information in this frontend demo.</p><label>Name<input defaultValue="User"/></label><label>Email<input defaultValue="user@example.com"/></label><label>Medical information<textarea rows="4" placeholder="Optional notes"/></label><Button onClick={()=>alert('Profile changes saved in this demo.')}>Save Changes</Button></div></DashboardLayout>}
function SettingsPage(){return <DashboardLayout><div className="settingsPage card"><h1>Settings</h1><p>Demo preferences for the CareNexus frontend.</p>{['Email notifications','Medicine reminders','Appointment reminders','Privacy mode'].map((x,i)=><label className="switchRow" key={x}><span>{x}<small>Frontend demo preference</small></span><input type="checkbox" defaultChecked={i<3}/></label>)}<Button onClick={()=>alert('Settings saved in this demo.')}>Save Settings</Button></div></DashboardLayout>}
function Admin(){return <DashboardLayout><PageHero title="Admin Dashboard" text="Separate administration area for managing CareNexus content and user-facing resources." art="doctor"/><div className="statGrid"><Stat title="Users" value="—" icon="👥"/><Stat title="Cancer Information" value={cancerTypes.length} icon="🎗️"/><Stat title="Resources" value="—" icon="📚"/><Stat title="Messages" value="—" icon="✉️"/></div><div className="detailGrid"><InfoBlock title="Users"><p>Manage registered users after connecting authentication and a backend.</p></InfoBlock><InfoBlock title="Cancer Information"><p>Add, edit or remove cancer education entries from the content store.</p></InfoBlock><InfoBlock title="Symptoms & Emergency Resources"><p>Maintain warning signs and emergency resource content.</p></InfoBlock><InfoBlock title="Articles & Donations"><p>Manage awareness articles and verified donation organizations.</p></InfoBlock></div></DashboardLayout>}
function InfoPage({title,text,icon}){return <DashboardLayout><PageHero title={title} text={text} art={icon||'doctor'}/><div className="detailGrid"><InfoBlock title="Coming with the backend"><p>This frontend provides the page structure and interaction. Persistent data, authentication, notifications and external integrations require a backend/API.</p></InfoBlock></div></DashboardLayout>}
function Empty({text}){return <div className="empty card"><Search/><h2>{text}</h2><Button to="/cancer">View Cancer Information</Button></div>}

function App(){return <Routes>
<Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/cancer" element={<Cancer/>}/><Route path="/cancer/:id" element={<CancerDetails/>}/><Route path="/symptoms" element={<Symptoms/>}/><Route path="/emergency" element={<Emergency/>}/><Route path="/medicine" element={<Medicine/>}/><Route path="/appointments" element={<Appointments/>}/><Route path="/mental-health" element={<MentalHealth/>}/><Route path="/mental-health/:id" element={<MentalDetail/>}/><Route path="/resources" element={<Resources/>}/><Route path="/donate" element={<Donate/>}/><Route path="/contact" element={<Contact/>}/><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Login signup/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/profile" element={<Profile/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<Navigate to="/"/>}/>
</Routes>}
export default App;
